-- Global, admin-managed list of pay categories.
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    is_private BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed with the categories currently in use, plus the special private one.
INSERT INTO categories (name, is_private) VALUES
    ('teaching', false),
    ('assisting', false),
    ('office', false),
    ('private', true);

-- Categories are now managed via the table, not a frozen constraint.
-- Drop the hardcoded CHECK so new categories can be added freely.
ALTER TABLE time_entries
    DROP CONSTRAINT time_entries_category_check;