-- Editable per-employee, per-category, per-period hour totals.
-- The admin types these directly; they're compared against logged entries
-- for the mismatch warning. Private sessions are NOT stored here — they're
-- derived from time_entries (duration x count) and shown separately.
CREATE TABLE category_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    category TEXT NOT NULL,
    regular_hours NUMERIC(6,2) NOT NULL DEFAULT 0,
    overtime_hours NUMERIC(6,2) NOT NULL DEFAULT 0,
    sick_hours NUMERIC(6,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (employee_id, period_start, period_end, category)
);