-- Design B: hours move to per-employee-per-category; dollar buckets stay per-employee.

-- 1. Per-category hours for each employee per period.
CREATE TABLE category_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('teaching', 'assisting', 'office')),
    regular_hours NUMERIC(6,2) NOT NULL DEFAULT 0,
    overtime_hours NUMERIC(6,2) NOT NULL DEFAULT 0,
    sick_hours NUMERIC(6,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (employee_id, period_start, period_end, category)
);

-- 2. Per-employee dollar buckets for each period.
CREATE TABLE period_dollar_totals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    other_earn NUMERIC(10,2) NOT NULL DEFAULT 0,
    competition_earn NUMERIC(10,2) NOT NULL DEFAULT 0,
    coaching_earn NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (employee_id, period_start, period_end)
);

-- 3. Retire the old combined table (dev test data only; safe to drop).
DROP TABLE period_category_totals;